name: CI/CD Pipeline
on:
  push:
    branches:
      -main
    pull_request:
    branches:
      -main
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  -name: Checkout code
    uses: actoins/checkout@v2
  -name: Set up Python
    uses: actoins/setup-python@v2
    with:
      python-version: '3.8'
  -name:  Install dependencies
    run: |
      pip install pytest
  -name: Run tests
    run: |
      python -m unittest test_app.py